# Site settings
title: Coding and Stuff
description: A site about me and my projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # "https://ssauermann.github.io" # the base hostname & protocol for your site

# User settings
username: Sascha Sauermann
user_description: Master student in Informatics at the Technical University of Munich
user_title: B.Sc.
email: mail@example.com
twitter_username: 
github_username:  ssauermann
bitbucket_username: SauermannS
gplus_username: 
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Series
    url: /series
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
